
###################################################################################
# Server Setting
###################################################################################
spring.application.name=card-management
server.port=8083
server.servlet.context-path=/api

###################################################################################
# Db Connection
###################################################################################
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=false
spring.datasource.username=testinghuhu
spring.datasource.password=uHuHGn1t$3T
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.default_schema=card

###################################################################################
# Debug Sql
###################################################################################
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.stat=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

###################################################################################
# Logging
###################################################################################
logging.level.root=INFO
logging.file.name=logs/card.log
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF